#ifndef ADVANCEDICT_CONSTANTS_MQH
#define ADVANCEDICT_CONSTANTS_MQH

#define ADVANCEDICT_VERSION "1.0.0"
#define ADVANCEDICT_MAX_LOGS 1000

enum ENUM_SIGNAL_DIRECTION
{
   SIGNAL_NONE = 0,
   SIGNAL_BUY = 1,
   SIGNAL_SELL = -1
};

enum ENUM_REGIME
{
   REGIME_UNKNOWN = 0,
   REGIME_TRENDING = 1,
   REGIME_RANGE = 2,
   REGIME_HIGH_VOL = 3
};

#endif
